### ISSUE TITLE
Detekt 1.18 not found

### ISSUE THREAD

**Issue by VaiTon** [peter-murray/setup-detekt#1]
workflow file: 

```yml
env:
  # Release tag associated with version of Detekt to be installed
  # SARIF support (required for this workflow) was introduced in Detekt v1.15.0
  DETEKT_RELEASE_TAG: v1.18.0

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup detekt
        uses: peter-murray/setup-detekt@v1
        with:
          detekt_version: ${{ env.DETEKT_RELEASE_TAG }}

      # Performs static analysis using Detekt
      - name: Run Detekt
        continue-on-error: true
        run: |
          detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json

      # Uploads results to GitHub repository using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ github.workspace }}/detekt.sarif.json
          checkout_path: ${{ github.workspace }}
```

![immagine](https://user-images.githubusercontent.com/12072630/130627454-4b1f133a-792d-4000-b701-6b0224803a19.png)
